config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/about', to: 'about#show', as: :about
  get '/logout', to: 'sessions#destroy', as: :logout

  get '/auth/facebook', as: :facebook_login

  get 'auth/facebook/callback', to: 'sessions#create'
  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get '/profile', to: 'users#show', as: :profile

  resources :users, only: [:edit, :update]

  resources :events do
    resources :event_attendees, only: [:create, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/credential.rb
class Credential < ApplicationRecord
  validates_presence_of :uid
  validates_presence_of :provider
  validates_presence_of :token

  belongs_to :user

  def self.find_or_create_by_omniauth(auth)
    if auth["provider"] == "facebook"
      info = "credentials"
    else
      info = "info"
    end

    find_or_create_by(
      uid: auth["uid"],
      provider: auth["provider"],
      token: auth["#{info}"]["token"]
      )
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :date
  validates_presence_of :time
  validates_presence_of :address
  validates_presence_of :user_id
  validates_presence_of :radius

  belongs_to :user
  has_many :event_attendees

  def host_name
    user.name
  end
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :number_of_guests, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }

  enum rsvp: ["Not this time!", "Not sure yet!", "I'll be there!"]

  def self.attendees(event)
    joins(:user)
    .where("event_attendees.event_id = ?", "#{event.id}")
    .select("event_attendees.*")
    .select("users.name")
    .group(:id, "users.name")
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :name
  has_many :events
  has_many :event_attendees
  has_many :credentials

  def self.create_with_omniauth(auth)
    if auth[:provider] == "facebook"
      find_or_create_by(name: auth[:extra][:raw_info][:name])
    else
      find_or_create_by(name: auth[:info][:name])
    end
  end

  def add_credential(provider, auth)
    credentials.find_or_create_by_omniauth(auth)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :boolean_to_words

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def boolean_to_words(value)
    value ? "Yes" : "No"
  end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController


  def create
    @event = Event.find(params[:event_id])
    event_attendee = @event.event_attendees.new({
      user: current_user,
      rsvp: params[:rsvp].to_i,
      number_of_guests: params[:number_of_guests]
      })
    if @event.save
      flash[:success] = "Thank you for your response!"
      TwilioFacade.new.sendtext(1, current_user.phone)
    end
    redirect_to event_path(@event)
  end

  def update
    event = Event.find(params[:event_id])
    attendee = event.event_attendees.find_by(user_id: current_user.id)
    attendee.update(rsvp: params[:rsvp].to_i)
    attendee.update(number_of_guests: params[:number_of_guests].to_i)
    if attendee.save
      flash[:success] = "RSVP updated"
      redirect_to event_path(event)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :check_authorized_user

  def new
    @event = Event.new
  end

  def create
    event = current_user.events.create(event_params)
    if event.save
      flash[:success] = "#{event.title} was created!"
      TwilioFacade.new.sendtext(0, current_user.phone)
      redirect_to event_path(event)
    else
      flash[:error] = "There was an error: please try again."
      redirect_to new_event_path
    end
  end

  def edit
    @event = Event.find([params[:id]])
  end

  def index
    @events = Event.all
    render locals: {
      facade: LocalEventsFacade.new
    }
  end

  def update
    @event = Event.find(params[:id])
    if current_user.id == @event.user_id
      @event.update(event_params)
      redirect_to event_path(@event)
    else
      render file: 'public/404', status: 404
    end
  end

  def show
    @event = Event.find(params[:id])
    address = @event.address
    render locals: {
      facade: EventLocationFacade.new(address, params[:id])
    }
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:success] = "Your event has been deleted."
    TwilioFacade.new.sendtext(2, current_user.phone)
    redirect_to events_path
  end

  private
    def event_params
      params.require(:event).permit(:title, :date, :time, :address, :user_id, :event_type, :food, :booze, :restrictions, :radius)
    end

    def check_authorized_user
      render file: 'public/404', status: 404 unless !current_user.address.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new;end

  def create
    auth = request.env["omniauth.auth"]
    user = User.create_with_omniauth(auth)
    session[:user_id] = user.id
    current_user.add_credential(auth[:provider], auth)

    redirect_to profile_path
    flash[:success] = "Successfully logged in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = current_user
  end

  def show
  end

  def update
    user = current_user
    user.update(user_params)
    flash[:success] = "Welcome to your profile, #{user.name}!"
    redirect_to profile_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :address, :city, :state, :zip, :phone, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/events/_form.html.erb
  <section>

    <div class="col-xl ">
    <div class="col-xl container4" style="align-content: center; flex-wrap: wrap;">
    <div class="text-center shadow-lg p-3 mb-5 bg- rounded label-style" >
    <%= form_for @event do |form| %>
      <div>
        <h2><%= form.label :title %></h2>
        <h2><%= form.text_field :title %></h2>
      </div>
      <div>
        <h2><%= form.label :date %></h2>
        <h2><%= form.text_field :date %></h2>
      </div>
      <div>
        <h2><%= form.label :time %></h2>
        <h2><%= form.text_field :time %></h2>
      </div>
      <div>
        <h2><%= form.label :address %></h2>
        <h2><%= form.text_field :address %></h2>
      </div>
      <div>
        <h2><%= form.label :event_type %></h2>
        <h2><%= form.text_field :event_type %></h2>
      </div>
      <div>
        <h2><%= form.label :restrictions %></h2>
        <h2><%= form.text_field :restrictions %></h2>
      </div>
      <div>
        <h2><%= form.label :radius_in_miles %></h2>
        <h2><%= form.text_field :radius %></h2>
      </div>
      <div>
        <h2><%= form.label :food %>    <%= form.check_box :food %></h2>
      </div>
      <div>
        <h2><%= form.label :booze %>    <%= form.check_box :booze %></h2>
      </div>
      <%= form.submit %>
    <% end %>

    </div>

    </div>
    </div>



  </section>
  </main>
</div>

app/views/events/_rsvp.html.erb
<%= form_tag path, method: method do %>
  <%= label_tag :your_response %>
  <%= select_tag :rsvp, options_for_select(EventAttendee.rsvps) %>
  <br>
  <%= label_tag :number_of_guests %>
  <%= number_field_tag :number_of_guests %>
  <%= submit_tag button_text %>
<% end %>

app/views/events/_user_rsvp.html.erb
<%= form_tag event_event_attendees_path(@event), method: :post do %>
<%= select_tag :rsvp, options_for_select(EventAttendee.rsvps) %>
  <%= label_tag :number_of_guests %>
  <%= number_field_tag :number_of_guests %>
  <%= submit_tag "Edit RSVP" %>
<% end %>

app/views/events/edit.html.erb
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <h2 class="masthead-subheading mb-0">Edit the Event:</h2>
    <div class="edit-event">
      <main>
        <div class="col-xl"></div>
      <%= render partial: "form" %>
    </div>
  </div>
</header>

app/views/events/index.html.erb
<header class="masthead text-center text-white">
  <div class="wrap">
    <div class="masthead-content">
      <h2 class="masthead-subheading mb-0">Nearby Events in Your Neighborhood</h2>

      <section class="details-card">
        <div class="container-fluid">
          <div class="row">

          <% @events.each do |event| %>
              <div class="col-md-12 p-3">
                <% if facade.user_within_event_radius(current_user.address, event.address, event.radius) %>
                  <div class="card-content style="background-image:<%= image_path("flamingo_logo.png")%>;"" id='event-<%= event.id %>'>
                    <div class="card-header">
                      <h1 class="card-title text-center"><%= link_to event.title, event_path(event.id) %></h1>
                      <h1 class="date"><%= event.date %></h1>
                      <h1 class="time"><%= event.time %></h1>
                      <% if current_user.id == event.user_id %>
                      <div class="delete-event"><%= button_to "Delete Event", event_path(event), method: :delete, data: { confirm: "Are you sure?" } %></div>
                    </div>
                  </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </section>
      </div>
      <br>
    </div>
</header>

app/views/events/new.html.erb
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <h2 class="masthead-subheading mb-0">Create an Event:</h2>
    <div class="edit-event">
      <main>
      <%= render partial: "form" %>
    </div>
  </div>
</header>

app/views/events/show.html.erb
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div>

      <h2 class="masthead-subheading mb-0"><%= facade.specific_event.title %></h2>
      <% if current_user.id == facade.specific_event.user_id %>
        <%= button_to "Edit Event", edit_event_path(facade.specific_event), method: :get %>
      <% end %>
    </div><br>

    <% if current_user.id != facade.specific_event.user_id %>
    <div class='rsvp' style= "font-size: 20px;">
      <div class="label-style">

      <% if facade.event_attendees == [] %>
        <%= render partial: "rsvp", locals: { path: event_event_attendees_path(facade.specific_event.id), method: :post, button_text: "RSVP"} %>
      <% else %>
        <% facade.event_attendees.each do |event_attendee| %>
          <% if event_attendee.user_id == current_user.id  %>
            <%= render partial: "rsvp", locals: { path: event_event_attendee_path(facade.specific_event.id, event_attendee.id), method: :patch, button_text: "Edit RSVP" } %>
          <% else %>
             <%= render partial: "rsvp", locals: { path: event_event_attendees_path(facade.specific_event.id), method: :post, button_text: "RSVP"} %>
          <% end %>
        <% end %>
      <% end %>
      </div><br>
      </div>
    </div>
    <% end %>

<div class="text-left shadow-lg p-3 mb-5 bg- rounded" >
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl ">
        <div class="text-left shadow-lg p-3 mb-5 bg- rounded" >
          <h1> Date: <%= facade.specific_event.date %></h1>
          <h1> Time: <%= facade.specific_event.time %></h1>
          <h1> Host: <%= facade.specific_event.host_name %></h1>
          <h1> Address: <%= facade.specific_event.address %></h1>
          <h1> Type: <%= facade.specific_event.event_type %></h1>
          <h1> Bring Food? <%= boolean_to_words(facade.specific_event.food) %></h1>
          <h1> Bring Booze? <%= boolean_to_words(facade.specific_event.booze) %></h1>
          <h1> Special restrictions: <%= facade.specific_event.restrictions %></h1>
        </div>
      </div>

      <div class="col-xl">
        <div class="rounded-circle location_map">
        <iframe class='rounded'
          width="600"
          height="450"
          frameborder="0" style="border:0"
          src= "https://www.google.com/maps/embed/v1/place?key=<%= facade.key_location %>" allowfullscreen>
        </iframe></div>
    </div>
  </div>
  <div class='rsvp_list' style= "font-size: 20px;"><br>
    <h2>Who's RSVP'd:</h2>
    <% facade.event_attendees.each do |event_attendee| %>
      <p><%= event_attendee.name %> Reply: <%= event_attendee.rsvp %> Number of guests: <%= event_attendee.number_of_guests %></p>
    <% end %>
    </div>
  </div><br>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinkFlamingo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-6jHF7Z3XI3fF4XZixAuSu0gGKrXwoX/w3uFPxC56OtjChio7wtTGJWRW53Nhx6Ev" crossorigin="anonymous">

    <link href="https://blackrockdigital.github.io/startbootstrap-one-page-wonder/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

    <link href="https://blackrockdigital.github.io/startbootstrap-one-page-wonder/css/one-page-wonder.min.css" rel="stylesheet">

    <style type="text/css">@import url(https://fonts.googleapis.com/css?family=Lato:300,400,700,900);</style>
    <style type="text/css">@font-face { font-family: 'simple-line-icons'; src: url('chrome-extension://mihdfbecejheednfigjpdacgeilhlmnf/assets/fonts/Simple-Line-Icons.ttf') format('truetype'); }</style>
  </head>
  <body>
    <% if current_user  %>
      <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-item nav-link" style="font-size: 15px;" <%= link_to 'Profile', profile_path if current_user %>
              </li >
              <li class="nav-item">
                <a class="nav-item nav-link" style="font-size: 15px;" <%= link_to 'Events', events_path if current_user && !current_user.address.nil? %>
              <li class="nav-item">
                <a class="nav-item nav-link" style="font-size: 15px;" <%= link_to 'Logout', logout_path if current_user %>
              </li>
            </ul>
            <% if flash[:success] %>
              <div class="alert alert-success" style="position: absolute;
              left: 50px; font-size: 20px;">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash[:success] %>
              </div>
            <% elsif flash[:error] %>
              <div class="alert alert-warning" style="position: absolute;
              left: 50px; font-size: 20px;">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash[:error] %>
              </div>
            <% end %>
          </div>
          <a href="<%= root_path %>">
            <img src="<%= image_path("flamingo_logo.png") %>" style="width: 4%; position: absolute;
            right: 50px; margin-top: -23px" alt="logo">
          </a>
        </div>
      </nav>
    <% end %>
    <%= yield %>

    <footer class="py-5 bg-black">
      <div class="container">
        <p class="m-0 text-center text-white small">Copyright © Pink Flamingo 2019</p>
      </div>
    <!-- /.container -->
    </footer>

    <script src="https://blackrockdigital.github.io/startbootstrap-one-page-wonder/vendor/jquery/jquery.min.js"></script>
    <script src="https://blackrockdigital.github.io/startbootstrap-one-page-wonder/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script async="" id="dsq-count-scr" src="//startbootstrap.disqus.com/count.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous" type="text/javascript"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous" type="text/javascript"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.9/jquery.lazy.plugins.min.js"></script>
    <script src="/assets/js/scripts.js" type="text/javascript"></script>
    <script type="text/javascript">
    $("#desktopToggle").on('click', function(e) {
      e.preventDefault();
      $(".iframe-preview").removeClass("iframe-preview-mobile");
    });
    $("#mobileToggle").on('click', function(e) {
      e.preventDefault();
      $(".iframe-preview").addClass("iframe-preview-mobile");
    });
  </script>
  </body>
</html>

app/views/users/edit.html.erb
<header class="masthead text-center text-white">
  <div class="row"><div class="wrap">
    <div class="masthead-content">
      <div class="user-profile", style="font-size: 25px;"">
        <main>
          <h1>Fill Out Your Profile:</h1>
          <div>

            <div class="row">
            <div class="col-xl ">
            <div class="col-xl container4" style="align-content: center; flex-wrap: wrap;">
            <div class="text-center shadow-lg p-3 mb-5 bg- rounded" >
            <div class="label-style">

            <%= form_for @user, url: user_path(current_user), method: :patch do |form| %>
              <div>
              <br>
              <%= form.label :address %>
              <%= form.text_field :address %>
              </div>
              <br>
              <div>
              <%= form.label :city %>
              <%= form.text_field :city %>
              </div>
              <br>
              <div>
              <%= form.label :state %>
              <%= form.text_field :state %>
              </div>
              <br>
              <div>
              <%= form.label :zip %>
              <%= form.text_field :zip %>
              </div>
              <br>
              <div>
              <%= form.label :phone %>
              <%= form.telephone_field :phone %>
              </div>
              <br>
              <div>
              <%= form.label :email %>
              <%= form.email_field :email %>
              </div>
              <br>
              <%= form.submit 'Submit Profile Info' %>
            <% end %>
            </div>
          </div>
          </div>
          </div>
          </div>
          </div>
        </main>
      </div>
    </div>
  </div>
  </div>
</header>

app/views/users/new.html.erb
<div class="user-profile">
  <main>
<h4>Create Your Profile:</h4>
  <section>
    <%= form_for @user, url: user_path(current_user), method: :patch do |form| %>
      <div>
        <%= form.label :address %>
        <%= form.text_field :address %>
      </div>
      <div>
        <%= form.label :city %>
        <%= form.text_field :city %>
      </div>
      <div>
        <%= form.label :state %>
        <%= form.text_field :state %>
      </div>
      <div>
        <%= form.label :zip %>
        <%= form.text_field :zip %>
      </div>
      <div>
        <%= form.label :phone %>
        <%= form.telephone_field :phone %>
      </div>
      <div>
        <%= form.label :email %>
        <%= form.email_field :email %>
      </div>
      <%= form.submit 'Complete Profile' %>
    <% end %>
  </section>
  </main>
</div>

app/views/users/show.html.erb
<header class="masthead text-center text-white">
  <div class="wrap">
    <div class="masthead-content">
      <div class="container">
        <section id="user-info">
        <% if current_user.address.nil? %>
          <%= button_to "Complete your profile", edit_user_path(current_user), method: :get %>
        <% else %>
          <br>
          <h2 class="masthead-subheading mb-0">Welcome back, <%= current_user.name %>!</h2>
          <br>
          <div class="row">
          <div class="col-xl ">
          <div class="text-left shadow-lg p-3 mb-5 bg- rounded" >
          <h1>Profile Info:</h1>
          <h2 class="user-address"><%= current_user.address %></h2>
          <h2 class="user-state-zip"><%= current_user.city %>, <%= current_user.state %> <%= current_user.zip %></h2>
          <h2 class="user-phone"><%= current_user.phone %> </h2>
          <h2 class="user-email"><%= current_user.email %> </h2>
          </div>
          </div>
          </div>
          <br>
          <div class="row">
          <div class="col-xl ">
          <div class="text-left shadow-lg p-3 mb-5 bg- rounded" >
          <%= button_to "Update Profile", edit_user_path(current_user), method: :get %>
          <br>
          <%= button_to "Create an Event", new_event_path, method: :get %>
          <br>
          <%= button_to "Events in Your Neighborhood", events_path, method: :get %>
          <br>
          </div>
          </div>
          </div>
          </section>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/welcome/index.html.erb
<header class="masthead text-center text-white">
  <div class="wrap-welcome">
    <div class="masthead-content">
      <img src="<%= image_path("flamingo_logo.png")%>" alt="logo"><br><br>
      <div class="container">
        <h2 class="masthead-subheading mb-0">An app to bring you closer to your community</h2>
      </div>
    </div>
    <br>
    <% unless current_user %>
      <br>
      <%= button_to 'Connect via Facebook', facebook_login_path, method: :get %>
      <br>
      <%= button_to 'Connect via Google', '/auth/google_oauth2', method: :get %>
    <% end %>
    <br>
    <div class="container">
    <br>
      <p class="masthead-subheading mb-0" style="font-size: 20px;">What is Pink Flamingo?<br>
      <br>
        Our team designed the Pink Flamingo app with community in mind. With work schedules and job relocation forcing people to move more frequently, it can be hard to build relationships with the people right down the street. Let Pink Flamingo make this task easier! Pink Flamingo takes away the awkward first step of knocking on doors or cold calling neighbors you haven't met yet. Our app allows you to schedule casual gatherings at your home and invite everyone within a radius of your choosing. Guests can see the events in their area, RSVP and all members will be texted reminders as the party gets closer.<br>
        <br>
        For more spontaneous hang outs, Pink Flamingo offers a "Flock Party" option. Place your own Pink Flamingo outside of your house to let people know you are around and open to visitors. The Pink Flamingo's GPS tracking system will alert users that there is a "Flock Party" in session. If you decide to move the party down the street to another neighbor's house, just take your Pink Flamingo with you to let people know where they can catch up with the group!</p><br>
    </div>
  </div>
</header>